security:
    providers:
        backend_users:
            memory:
                users:
                    mazen_admin: { password: '123456789', roles: ['ROLE_ADMIN'] }
                    admin: { password: '987654321', roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN'] }
